config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  root "posts#index"

  get "/about", to: "pages#about"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # create comments
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  # delete comments
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

# about page
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  # to create new posts
  def new
    @post = Post.new
  end

  # to save posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  # defining a post
  def show
    @post = Post.find(params[:id])
  end

  # edit post
  def edit
    @post = Post.find(params[:id])
  end

  # update post
  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  # delete post
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end



  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %> </strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>

<% if user_signed_in? %>
  <p><%= link_to "Delete", [comment.post, comment],
                  method: :delete,
                  class: "button",
                  data: { confirm: "Are you sure?" } %>
  </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<!-- comment form partial -->
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raileway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
      <%= image_tag "logo.svg" %>
      <% end %>
    </div>

    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Weblog", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="https://www.linkedin.com/in/stefaniemknapp
        ">LinkedIn</a></li>
        <li><a href="https://twitter.com/stef_knapp">Twitter</a></li>
        <li><a href="https://github.com/sknapp0125">GitHub</a></li>
        <li><a href="mailto:sknapp0125@gmail.com">Email</a></li>
      </ul>

      <% if !user_signed_in? %>
      <p class="sign_in">Admin Login</p>
      <% end %>
    </div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>All Posts</p>
        <% elsif current_page?(about_path) %>
          <p>About</p>
        <% else %>
          <%= link_to "Back to All Posts", root_path %>
        <% end %>

        <% if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %></button>
          <button class="button">Log Out</button>
        </div>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
      <% end %>

      <%= yield %>

    </div>


  </body>
  </html>

app/views/pages/about.html.erb
<!-- About Page -->
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.jpg" %>
  </div>

  <div id="content">
    <h1>Hi, I'm Stefanie Knapp</h1>
    <p>I'm following Mackenzie Child's 12 Web Apps in 12 Weeks Challenge.</p>
    <p>This is Week 2, in which we build a blog in Ruby on Rails 4. This is the demo application. If this were live, this would say somthing else. Obviously.</p>
    <p>Here's some filler text, by way of Cat Ipsum. This is the Internet, after all...<br>
    "Cat ipsum dolor sit amet, burrow under covers. Vommit food and eat it again roll on the floor purring your whiskers off. Flop over attack dog, run away and pretend to be victim or eat a plant, kill a hand so chew on cable hide at bottom of staircase to trip human kitty loves pigs so unwrap toilet paper. Destroy couch lick arm hair if it fits, i sits jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed. Hack up furballs asdflkjaertvlkjasntvkjn (sits on keyboard) climb a tree, wait for a fireman jump to fireman then scratch his face unwrap toilet paper for kick up litter leave dead animals as gifts. Peer out window, chatter at birds, lure them to mouth sleep on dog bed, force dog to sleep on floor but bathe private parts with tongue then lick owner's face or where is my slave? I'm getting hungry stare out the window. Attack the dog then pretend like nothing happened. Eat prawns daintily with a claw then lick paws clean wash down prawns with a lap of carnation milk then retire to the warmest spot on the couch to claw at the fabric before taking a catnap climb leg. Cat is love, cat is life meow all night having their mate disturbing sleeping humans human is washing you why halp oh the horror flee scratch hiss bite. Behind the couch. Poop in the plant pot burrow under covers plan steps for world domination, so curl into a furry donut."</p>
  </div>
</div>

app/views/posts/_form.html.erb
<!-- post form partial -->
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/posts/edit.html.erb
<!-- Edit Posts -->
<div id="page_wrapper">
  <h1>Edit Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>

  </div>
<% end %>

app/views/posts/new.html.erb
<!-- New Posts -->
<div id="page_wrapper">
  <h1>New Post</h1>

  <!-- form for submtting posts -->
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<!-- Where the Posts live -->
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago
    <% if user_signed_in? %>
    | <%= link_to 'Edit', edit_post_path(@post) %>
    | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>

  <!-- comments -->
  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a Comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>